### ISSUE TITLE
Comments on Introduction

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [PeterHjortLauritzen/2017-MWR-physgrid#1]
0. "An aqua-planet simulation ..." Seems a little abrupt with the flow of the text. Maybe bridge the sentences with "To test this hypothesis we have ... APE ..." and "If this hypothesis was right it should not matter where we sample OMEGA ..."

1. Before the area argument perhaps you can spell out that the PDF of omega in APE setup should not depend on where you sample omega.

2. "... characteristically sluggish and intially at odds with the expectation."

What do you mean by "sluggish and initially at odds"?

3. After that, maybe start a new paragraph stating that the corner and edge notes are similar (in terms of OMEGA PDF) and that that does not seem to scale with area as much as interior versus corner/edge. (after all, the corners nodes are approximately a fourth of the size of the edge notes). And then you can start with the non-smoothness argument. In that case we have one paragraph with the area argument and one with the smoothness argument.

4. DSS - maybe reference our dry-mass paper and/or Ram's book chapter. Perhaps add a descriptive sentence explaining DSS (solutions evolving separately in each element and the only way element "feel" each other is through the averaging - DSS) - I know this is in the caption, so either repeat some of it here or spell out that this is explained in detail in the Figure caption. This is one of the most important feature of SE that we discuss in this manuscript so it has to be emphasized ...

5. Explain what C^0 means (I had a reviewer complain about that before ...)

**Comment by adamrher** [comment]
Peter, i think ive addressed most of your concerns, and the intro is much smoother in my opinion. Only remaining issue is working in a satisfactory definition of of DSS for the reader.
