### ISSUE TITLE
Acknowledge NCAR and CISL support 

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [PeterHjortLauritzen/2017-MWR-physgrid#3]
Be sure to acknowledge NCAR and CISL support in your publications

Acknowledging the support of NCAR and CISL computing when you publish research results helps ensure continued support from the National Science Foundation and other sources of funding for future high-performance computing (HPC) systems. It is also a requirement of receiving an allocation, as noted in your award letter.

The reporting requirements, how to cite your use of various systems, and recommended wording of acknowledgments can be found on this CISL web page. The content of citations and acknowledgments varies depending on the type of allocation that was awarded.

**Comment by gold2718** [comment]
Thanks for digging up the Multiscale info (copied below):
"Goldhaber was partially supported by the U.S. Department of Energy Office of Biological and Environmental Research, Work Package 12-015334 “Multiscale Methods for Accurate, Efficient, and Scale-Aware Models of the Earth System”."

I also need to thank ACME and the CSU Q3D program since they also paid for part of my physgrid work (in addition to some base funding which is already acknowledged).

**Comment by PeterHjortLauritzen** [comment]
I have CSU Q3D acknowledgement ready. Do you have award numbers for ACME?

**Comment by gold2718** [comment]
According to the E3SM page, the acknowledgement is supposed to read:

> This research was supported as part of the Energy Exascale Earth System Model (E3SM) project, formerly known as Accelerated Climate Modeling for Energy (ACME), funded by the U.S. Department of Energy, Office of Science, Office of Biological and Environmental Research.

Since my work was before the name change, maybe we should use:
> This research was supported as part of the Accelerated Climate Modeling for Energy (ACME) project, funded by the U.S. Department of Energy, Office of Science, Office of Biological and Environmental Research.
>

**Comment by brian-eaton** [comment]
I believe the NCAR/NFS acknowledgment covers me.

**Comment by paullric** [comment]
You can add me to the Multiscale Methods acknowledgement:

Goldhaber and Ullrich were partially supported by the U.S. Department of Energy Office of Biological and Environmental Research, Work Package 12-015334 “Multiscale Methods for Accurate, Efficient, and Scale-Aware Models of the Earth System”.

Best,

~ Paul
