### ISSUE TITLE
FIgures 7 & 8

### ISSUE THREAD

**Issue by adamrher** [PeterHjortLauritzen/2017-MWR-physgrid#5]
Make zero contour level easier to decipher. Replace 'level XX' with approximate pressure levels. Grid imprinting is not easy to decipher - maybe overlay se grid and make plot regional for easier interpretation.

**Comment by adamrher** [comment]
Proposed solution. Remove transect plot. It's only real purpose is to support the idea that imprinting over topo manifests as full-troposphere updrafts/downdrafts. This can be simply stated instead of shown. New contour plot based on an idea proposed by Eaton:
[temp_cellfill (1).pdf](https://github.com/PeterHjortLauritzen/2017-MWR-physgrid/files/1905369/temp_cellfill.1.pdf)

**Comment by brian-eaton** [comment]
The cell fill really helps to show how the boundary cells tend to have the extreme values.  I think this plot is a big improvement over the original.
